### ISSUE TITLE
Obfuscation should not happen on inputs

### ISSUE THREAD

**Issue by laulaz** [collective/collective.geotransform#15]
If you have a form with an `input` containing an email address, it gets obfuscated but it should not.

**Comment by tomgross** [comment]
I wonder how this happens, since the selector is `'a[href^=mailto:]'` in https://github.com/collective/collective.geotransform/blob/master/collective/geotransform/transform.py#L22

**Comment by laulaz** [comment]
@tomgross That's because of the other part : plain email addresses are also geotransformed. Not only links.

See https://github.com/collective/collective.geotransform/blob/master/collective/geotransform/transform.py#L34-L40
