### ISSUE TITLE
Keep href links with user unobfuscated

### ISSUE THREAD

**Issue by laulaz** [collective/collective.geotransform#20]
`collective.geotransform` is a bit too agressive in its obfuscation.
We have an example where a link with a username (not an email) is transformed in a wrong  way, resulting in a broken link.

Our example was :
```<a href="https://outlook.office365.com/owa/calendar/user@bar.com/bookings/">link</a>``` which was transformed into :
```<a href="https://outlook.office365.com/owa/calendar/<span class="geomailaddress">dXNlckBiYXIuY29t</span>/bookings/">link</a>```

Those kind of links should remain unobfuscated.

**Comment by boulch** [comment]
- Fixed in master (Plone >= 5)
- Fixed in branch 1.x (Plone 4)
    https://github.com/collective/collective.geotransform/tree/1.x
